# Ip adresses and port of hub servers
# Set the port in 'config.yml' in your ServerSelectorX folder
addresses:
- 'localhost:9782'

# Set this to the name of this server EXACTLY as specified in the bungeecord config.
server-name: ''

# How often the connector plugin sends placeholders (4 means once every 4 seconds)
# If you have multiple servers, it will ping them in order. The interval between each server is
# the send interval divided by the number of addresses. (4 addresses / send-interval 2 = interval 0.5 seconds)
send-interval: 2

debug: false

# don't touch this option unless you know you need to
password: "a"