# Addresses of servers to send data to (the server(s) with ServerSelectorX installed).
# Set the port in 'api.yml' in your ServerSelectorX folder
addresses:
- 'localhost:9782'

# Set this to the name of this server EXACTLY as specified in the bungeecord config.
server-name: ''

# How often the connector plugin sends placeholders, in seconds.
# If you have multiple servers, the plugin will ping all servers within this time,
# with a roughly consistent interval. For example:
# send-interval 2 / 4 addresses = every 0.5 seconds sending data to a server
send-interval: 4

debug: false

# Cache placeholders for some amount of seconds. Set to 0 to disable caching.
#cache:
#  placeholdername: 10

# Retrieve some placeholders asynchronously. Use with caution, only use with plugins that
# can handle being called async. Especially if you use this with placeholders related to
# players or worlds, stuff can break.
# async:
#  - placeholdername

# This should generally be set to true. Set it to false for debugging issues
# that may be related to caching.
enable-caching: true

# don't touch this option unless you know you need to
password: "a"